apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: kubesec
  namespace: openfaas-fn
spec:
  name: kubesec
  image: docker.io/stefanprodan/kubesec:v2.1
  readOnlyRootFilesystem: false
  annotations:
    com.openfaas.health.http.initialDelay: 10s
    com.openfaas.health.http.path: /healthz
